name: user_repository
description: A repository to manage the user domain layer.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  rxdart: ^0.27.7
  treasure_hunter_api_client:
    path: ../treasure_hunter_api_client
  treasures_repository:
    path: ../treasures_repository

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  very_good_analysis: ^5.1.0
