name: treasure_hunter
description: A treasure hunting app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  persistent_storage:
    path: packages/storage/persistent_storage
  shared_preferences: ^2.3.1
  treasure_hunter_api_client:
    path: packages/treasure_hunter_api_client
  treasures_repository:
    path: packages/treasures_repository
  user_repository:
    path: packages/user_repository
  form_inputs:
    path: packages/form_inputs

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
